### ISSUE TITLE
[FE] [FEATURE] 중고 상품(상세) HTML & CSS

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_FE#10]
## 설명
중고 상품(상세) 화면 단을 HTML & CSS로 구현합니다.

## To-do
- [x] 상품 이미지박스 구현
- [x] 상품 정보 및 판매장 정보 관련 박스 구현
- [x] 찜하기, 쪽지 보내기, 삭제하기, 수정하기 버튼 구현하기
- [x] 상품정보 문단, 거래희망장소 문단 박스 구현

## ETC
CSS보다 HTML 기능에 집중해야 합니다.

**Comment by ksostuft** [comment]
11월 2일 팀원과 컴포넌트 관련 논의함
