### ISSUE TITLE
[FE] [FEATURE] 관심목록 HTML & CSS

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_FE#11]
## 설명
관심목록 화면 단을 HTML & CSS로 구현합니다.

## To-do
- [x] 관심목록 th 구현
- [x] 관심목록 tr 구현
- [x] 삭제 버튼 구현

## ETC
CSS보다 HTML 기능에 집중해야 합니다.

**Comment by ksostuft** [comment]
11월 2일 팀원과 컴포넌트 관련 논의함
