### ISSUE TITLE
[FE] [FEATURE] 상품 상세 조회

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_FE#19]
## 설명
상품 상세 페이지 화면 및 기능 구현

## To-do
- [x] 상품 정보 화면 구현
- [x] 상품 카테고리 줄 구현
- [x] 판매자 정보란 화면 구현
- [x] 상품 설명, 거래희망장소 정보란 화면 구현
- [x] 상품 정보 출력 기능 구현
- [x] 판매자 정보 출력 기능 구현
- [x] 상품 설명, 거래희망장소 정보 출력 기능 구
 및 기능 구현
- [x] 버튼 붙이기 및 기능 구현: 쪽지 보내기, 찜하기, 수정하기, 삭제하기
