### ISSUE TITLE
[FE] [FEATURE] 꾸러미 박스 컴포넌트

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_FE#30]
## 설명
꾸러미 박스 컴포넌트 화면 및 기능 구현

## To-do
- [ ] 예산 설정 화면 구현
- [ ] 꾸러미 박스 담는 화면 구현
- [ ] 예산 설정 기능 구현
- [ ] 박스에 상품을 담고 취소할 수 있는 기능 구현
