### ISSUE TITLE
[FE] [FEATURE] 꾸러미 HTML & CSS

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_FE#5]
## 설명
꾸러미 화면 단을 HTML & CSS로 구현합니다.

## To-do
- [x] 카테고리 박스 구현(중고 상품 공통)
- [x] 꾸러미 카테고리 선택박스 구현
- [x] 꾸러미 박스 구현
- [x] 정렬 필터 구현(중고 상품 공통)
- [x] 상품 박스 구현(중고 상품 공통)
- [x] 버튼 구현: 담기, 검색, 설정, 쪽지보내기
- [x] 디자인 맞추기

## ETC
CSS보다 HTML 기능에 집중해야 합니다.

**Comment by ksostuft** [comment]
11월 2일 팀원과 컴포넌트 관련 논의함
