### ISSUE TITLE
[FE] [FEATURE] 중고 상품(목록) HTML & CSS

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_FE#9]
## 설명
중고 상품(목록) 화면 단을 HTML & CSS로 구현합니다.

## To-do
- [x] 카테고리 박스 구현(중고 상품 공통)
- [x] 정렬 필터 구현(중고 상품 공통)
- [x] 가격 범위 검색 박스 구현 + 검색 버튼
- [x] 상품 박스 구현(중고 상품 공통)
- [x] 디자인 맞추기

## ETC
CSS보다 HTML 기능에 집중해야 합니다.

**Comment by ksostuft** [comment]
11월 2일 팀원과 컴포넌트 관련 논의함
